### ISSUE TITLE
Concurrency Question

### ISSUE THREAD

**Issue by MarkSonghurst** [uw-labs/go-onfido#6]
Thank you for a great Go package. My API is Go based and I have a need to interface it with Onfido. Finding your well documented package has saved me many days of development effort.

Are you able to confirm please, that the package (go-onfido.Client in particular) is safe for concurrent use by multiple Go routines?

Have you considered adding it here: https://documentation.onfido.com/#client-libraries

Thanks again. 
Mark

**Comment by SpeedyCoder** [comment]
Hi Mark

The client uses an instance of the following interface to call the api
```
type HTTPRequester interface {
	Do(*http.Request) (*http.Response, error)
}
```
If you use one of the provided constructors, then it will use `http.DefaultClient`, which is safe for concurrent use (check the [docs](https://golang.org/src/net/http/client.go) for more info) and therefore the `onfido.Client` is as well (technically this is only true if you don't change the fields of the struct after initialisation, but that's the responsibility of the user). This is also the case if you use an instance of the `http.Client` (you might want to do this to specify timeout for example). In case you use your own implementation of the `onfido.HTTPRequester` interface, you need to make sure that it's safe for concurrent use.

I don't think that we have considered contacting Onfido folks to list this library in their docs, but we might do that after using the library a little longer.

**Comment by MarkSonghurst** [comment]
Thanks.
